# LangChain Data Analysis Agent

Free stack: Groq API + LangChain + pandas.
Get a free API key at https://console.groq.com/keys

### 1. Install

In [1]:
!pip install -q langchain langchain-groq langchain-experimental pandas matplotlib tabulate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.2/211.2 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 103.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 65.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

### 2. API key

In [2]:
import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("Groq API key: ")

Groq API key: ··········

### 3. Sample data

In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 500

cities = ["Karachi", "Lahore", "Islamabad", "Sukkur", "Multan"]
categories = ["Laptop", "Phone", "Tablet", "Headphones", "Smartwatch"]
channels = ["Online", "Retail Store", "Reseller"]

prices = {
    "Laptop": 850,
    "Phone": 420,
    "Tablet": 300,
    "Headphones": 60,
    "Smartwatch": 150,
}

df = pd.DataFrame({
    "order_id": range(10001, 10001 + n),
    "date": pd.date_range("2024-01-01", periods=n, freq="D"),
    "city": np.random.choice(cities, n),
    "category": np.random.choice(categories, n),
    "channel": np.random.choice(channels, n, p=[0.5, 0.3, 0.2]),
    "units": np.random.randint(1, 15, n),
    "customer_age": np.random.randint(18, 65, n),
    "rating": np.round(np.random.uniform(2.0, 5.0, n), 1),
    "returned": np.random.choice([0, 1], n, p=[0.9, 0.1]),
})

df["unit_price"] = df["category"].map(prices)
df["discount_pct"] = np.random.choice([0, 5, 10, 15, 20], n)
df["revenue"] = (df["units"] * df["unit_price"] * (1 - df["discount_pct"] / 100)).round(2)
df["month"] = df["date"].dt.strftime("%Y-%m")

df.head(10)

,order_id,date,city,category,channel,units,customer_age,rating,returned,unit_price,discount_pct,revenue,month
0,10001,2024-01-01,Sukkur,Headphones,Reseller,7,49,2.4,0,60,20,336.0,2024-01
1,10002,2024-01-02,Multan,Laptop,Retail Store,12,28,2.9,0,850,15,8670.0,2024-01
2,10003,2024-01-03,Islamabad,Smartwatch,Retail Store,1,27,4.6,0,150,10,135.0,2024-01
3,10004,2024-01-04,Multan,Tablet,Reseller,8,26,5.0,0,300,10,2160.0,2024-01
4,10005,2024-01-05,Multan,Tablet,Retail Store,11,31,3.1,0,300,15,2805.0,2024-01
5,10006,2024-01-06,Lahore,Laptop,Online,13,30,3.3,0,850,15,9392.5,2024-01
6,10007,2024-01-07,Islamabad,Headphones,Retail Store,3,42,4.2,1,60,15,153.0,2024-01
7,10008,2024-01-08,Islamabad,Headphones,Retail Store,11,19,4.7,0,60,10,594.0,2024-01
8,10009,2024-01-09,Islamabad,Smartwatch,Online,6,52,3.8,0,150,15,765.0,2024-01
9,10010,2024-01-10,Multan,Laptop,Retail Store,9,24,3.2,0,850,0,7650.0,2024-01

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      500 non-null    int64
 1   date          500 non-null    datetime64[ns]
 2   city          500 non-null    object
 3   category      500 non-null    object
 4   channel       500 non-null    object
 5   units         500 non-null    int64
 6   customer_age  500 non-null    int64
 7   rating        500 non-null    float64
 8   returned      500 non-null    int64
 9   unit_price    500 non-null    int64
 10  discount_pct  500 non-null    int64
 11  revenue       500 non-null    float64
 12  month         500 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(6), object(4)
memory usage: 50.9+ KB

In [ ]:
df.describe()

,order_id,date,units,customer_age,rating,returned,unit_price,discount_pct,revenue
count,500.000000,500,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,10250.500000,2024-09-06 12:00:00,7.472000,40.518000,3.48920,0.110000,355.480000,9.370000,2415.175000
min,10001.000000,2024-01-01 00:00:00,1.000000,18.000000,2.00000,0.000000,60.000000,0.000000,51.000000
25%,10125.750000,2024-05-04 18:00:00,4.000000,29.000000,2.80000,0.000000,150.000000,5.000000,600.000000
50%,10250.500000,2024-09-06 12:00:00,7.000000,40.000000,3.50000,0.000000,300.000000,10.000000,1578.000000
75%,10375.250000,2025-01-09 06:00:00,11.000000,52.000000,4.20000,0.000000,420.000000,15.000000,3315.000000
max,10500.000000,2025-05-14 00:00:00,14.000000,64.000000,5.00000,1.000000,850.000000,20.000000,11900.000000
std,144.481833,NaN,4.014655,13.386863,0.85317,0.313203,277.020306,7.194207,2520.048996

### 4. Build the agent

In [4]:
from langchain_groq import ChatGroq
from langchain_experimental.agents import create_pandas_dataframe_agent

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
)

agent = create_pandas_dataframe_agent(
    llm,
    df,
    verbose=True,
    allow_dangerous_code=True,
    agent_type="tool-calling",
    max_iterations=10,
)

/tmp/ipykernel_990/2760974596.py:2: DeprecationWarning: `langchain-experimental` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-experimental/issues/87 for details.
  from langchain_experimental.agents import create_pandas_dataframe_agent

### 5. Helper function

In [5]:
def ask(question):
    result = agent.invoke(question)
    output = result["output"]
    print("\n" + "-" * 70)
    return output

### 6. Basic queries

In [6]:
ask("How many rows and columns? List the column names and their data types.")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "import pandas as pd\ndf = pd.DataFrame({'order_id': [10001, 10002, 10003, 10004, 10005], 'date': ['2024-01-01 00:00:00', '2024-01-02 00:00:00', '2024-01-03 00:00:00', '2024-01-04 00:00:00', '2024-01-05 00:00:00'], 'city': ['Sukkur', 'Multan', 'Islamabad', 'Multan', 'Multan'], 'category': ['Headphones', 'Laptop', 'Smartwatch', 'Tablet', 'Tablet'], 'channel': ['Reseller', 'Retail Store', 'Retail Store', 'Reseller', 'Retail Store'], 'units': [7, 12, 1, 8, 11], 'customer_age': [49, 28, 27, 26, 31], 'rating': [2.4, 2.9, 4.6, 5.0, 3.1], 'returned': [0, 0, 0, 0, 0], 'unit_price': [60, 850, 150, 300, 300], 'discount_pct': [20, 15, 10, 10, 15], 'revenue': [336, 8670, 135, 2160, 2805], 'month': ['2024-01', '2024-01', '2024-01', '2024-01', '2024-01']})\nprint(df.shape)\nprint(df.columns)\nprint(df.dtypes)"}`


(5, 13)
Index(['order_id', 'date', 'city', 'category', 'channel', 'units',
       'customer_age', 'rating', 'returned', 'unit_price', 'discount_pct',
       'revenue', 'month'],
      dtype='object')
order_id          int64
date             object
city             object
category         object
channel          object
units             int64
customer_age      int64
rating          float64
returned          int64
unit_price        int64
discount_pct      int64
revenue           int64
month            object
dtype: object
The dataframe has 5 rows and 13 columns. The column names and their data types are:

1. order_id - int64
2. date - object
3. city - object
4. category - object
5. channel - object
6. units - int64
7. customer_age - int64
8. rating - float64
9. returned - int64
10. unit_price - int64
11. discount_pct - int64
12. revenue - int64
13. month - object

Note: The 'object' data type in pandas typically represents a string or a categorical value. The 'int64' data type represents a 64-bit integer, and the 'float64' data type represents a 64-bit floating point number.

> Finished chain.

----------------------------------------------------------------------

"The dataframe has 5 rows and 13 columns. The column names and their data types are:\n\n1. order_id - int64\n2. date - object\n3. city - object\n4. category - object\n5. channel - object\n6. units - int64\n7. customer_age - int64\n8. rating - float64\n9. returned - int64\n10. unit_price - int64\n11. discount_pct - int64\n12. revenue - int64\n13. month - object\n\nNote: The 'object' data type in pandas typically represents a string or a categorical value. The 'int64' data type represents a 64-bit integer, and the 'float64' data type represents a 64-bit floating point number."

In [ ]:
ask("What is the total revenue across all orders?")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df['revenue'].sum()"}`


14106The total revenue across all orders is 14106.

> Finished chain.

----------------------------------------------------------------------
The total revenue across all orders is 14106.

'The total revenue across all orders is 14106.'

In [ ]:
ask("Which city has the highest total revenue? Show the full ranking with numbers.")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'import pandas as pd\ndf = pd.DataFrame({"order_id": [10001, 10002, 10003, 10004, 10005], "date": ["2024-01-01 00:00:00", "2024-01-02 00:00:00", "2024-01-03 00:00:00", "2024-01-04 00:00:00", "2024-01-05 00:00:00"], "city": ["Sukkur", "Multan", "Islamabad", "Multan", "Multan"], "category": ["Headphones", "Laptop", "Smartwatch", "Tablet", "Tablet"], "channel": ["Reseller", "Retail Store", "Retail Store", "Reseller", "Retail Store"], "units": [7, 12, 1, 8, 11], "customer_age": [49, 28, 27, 26, 31], "rating": [2.4, 2.9, 4.6, 5.0, 3.1], "returned": [0, 0, 0, 0, 0], "unit_price": [60, 850, 150, 300, 300], "discount_pct": [20, 15, 10, 10, 15], "revenue": [336, 8670, 135, 2160, 2805], "month": ["2024-01", "2024-01", "2024-01", "2024-01", "2024-01"]})\nprint(df.groupby(\'city\')[\'revenue\'].sum().sort_values(ascending=False))'}`


city
Multan       13635
Sukkur         336
Islamabad      135
Name: revenue, dtype: int64
The city with the highest total revenue is Multan, with a total revenue of 13635. The full ranking is:

1. Multan - 13635
2. Sukkur - 336
3. Islamabad - 135

This means that Multan has the highest total revenue, followed by Sukkur and then Islamabad.

> Finished chain.

----------------------------------------------------------------------
The city with the highest total revenue is Multan, with a total revenue of 13635. The full ranking is:

1. Multan - 13635
2. Sukkur - 336
3. Islamabad - 135

This means that Multan has the highest total revenue, followed by Sukkur and then Islamabad.

'The city with the highest total revenue is Multan, with a total revenue of 13635. The full ranking is:\n\n1. Multan - 13635\n2. Sukkur - 336\n3. Islamabad - 135\n\nThis means that Multan has the highest total revenue, followed by Sukkur and then Islamabad.'

In [ ]:
ask("What is the average rating per category, sorted highest to lowest?")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'import pandas as pd\ndf = pd.DataFrame({"order_id": [10001, 10002, 10003, 10004, 10005], "date": ["2024-01-01 00:00:00", "2024-01-02 00:00:00", "2024-01-03 00:00:00", "2024-01-04 00:00:00", "2024-01-05 00:00:00"], "city": ["Sukkur", "Multan", "Islamabad", "Multan", "Multan"], "category": ["Headphones", "Laptop", "Smartwatch", "Tablet", "Tablet"], "channel": ["Reseller", "Retail Store", "Retail Store", "Reseller", "Retail Store"], "units": [7, 12, 1, 8, 11], "customer_age": [49, 28, 27, 26, 31], "rating": [2.4, 2.9, 4.6, 5, 3.1], "returned": [0, 0, 0, 0, 0], "unit_price": [60, 850, 150, 300, 300], "discount_pct": [20, 15, 10, 10, 15], "revenue": [336, 8670, 135, 2160, 2805], "month": ["2024-01", "2024-01", "2024-01", "2024-01", "2024-01"]})\nprint(df.groupby(\'category\')[\'rating\'].mean().sort_values(ascending=False))'}`


category
Smartwatch    4.60
Tablet        4.05
Laptop        2.90
Headphones    2.40
Name: rating, dtype: float64
The average rating per category, sorted highest to lowest, is:

1. Smartwatch: 4.60
2. Tablet: 4.05
3. Laptop: 2.90
4. Headphones: 2.40

This indicates that Smartwatch has the highest average rating, followed by Tablet, Laptop, and then Headphones.

> Finished chain.

----------------------------------------------------------------------
The average rating per category, sorted highest to lowest, is:

1. Smartwatch: 4.60
2. Tablet: 4.05
3. Laptop: 2.90
4. Headphones: 2.40

This indicates that Smartwatch has the highest average rating, followed by Tablet, Laptop, and then Headphones.

'The average rating per category, sorted highest to lowest, is:\n\n1. Smartwatch: 4.60\n2. Tablet: 4.05\n3. Laptop: 2.90\n4. Headphones: 2.40\n\nThis indicates that Smartwatch has the highest average rating, followed by Tablet, Laptop, and then Headphones.'

### 7. Grouping and aggregation

In [ ]:
ask("Show total revenue and total units for each channel.")

In [ ]:
ask("Which month had the highest revenue? Show all months sorted by revenue.")

In [ ]:
ask("What is the return rate per category? Show it as a percentage.")

### 8. Multi-step reasoning

In [ ]:
ask("""Compare the Online and Retail Store channels.
For each one show total revenue, average order value, average rating, and return rate.
Then state which channel performs better and why.""")

In [ ]:
ask("""Find the top 3 city and category combinations by revenue.
For each show revenue, units sold, and average discount percentage.""")

In [ ]:
ask("""Split customers into age groups: 18-29, 30-44, and 45-64.
For each group show total revenue, average rating, and most purchased category.""")

### 9. Charts

In [ ]:
import matplotlib.pyplot as plt

ask("""Create a bar chart of total revenue by city.
Add a title and axis labels. Call plt.show() at the end.""")

NameError: name 'ask' is not defined

In [ ]:
ask("""Create a line chart of monthly revenue over time.
Rotate the x labels 45 degrees, add a title and axis labels.
Call plt.show() at the end.""")

In [ ]:
ask("""Create a grouped bar chart of revenue by category split by channel.
Add a legend, title, and axis labels. Call plt.show() at the end.""")

In [ ]:
ask("""Create a histogram of customer ratings using 15 bins.
Add a title and axis labels. Call plt.show() at the end.""")

### 10. Insights

In [ ]:
ask("""Act as a business analyst.
Find 3 insights from this data that are not immediately obvious.
For each give the finding, the supporting numbers, and one recommendation.""")

In [ ]:
ask("""Does discount level affect the return rate?
Group by discount_pct, show the return rate for each level, and state your conclusion.""")

### 11. Use your own CSV

In [ ]:
# Upload a CSV with the file panel on the left, then uncomment and run.

# df = pd.read_csv("/content/your_file.csv")
#
# agent = create_pandas_dataframe_agent(
#     llm,
#     df,
#     verbose=True,
#     allow_dangerous_code=True,
#     agent_type="tool-calling",
#     max_iterations=10,
# )
#
# ask("Describe this dataset and suggest questions I could ask about it.")

### 12. Your own questions

In [ ]:
ask("")

### Notes

- `allow_dangerous_code=True` executes generated Python in this runtime. Use only with data you can afford to lose.
- Chart not appearing: add "call plt.show()" to the question.
- Agent looping: make the question more specific or raise `max_iterations`.
- Rate limit error: wait one minute and rerun.
- To verify an answer, ask: "show me the pandas code you used".
- To run offline with Ollama, replace the llm line with:

```python
from langchain_ollama import ChatOllama
llm = ChatOllama(model="llama3.1")
```